# Generated by Django 5.1.4 on 2025-05-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socnetuser',
            name='confirmation_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
